export const data = [
  {
    id: 1,
    name: 'Shirt',
    price: 20,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 2,
    name: 'Pants',
    price: 30,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 3,
    name: 'Shoes',
    price: 50,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 4,
    name: 'Socks',
    price: 5,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 5,
    name: 'Jacket',
    price: 60,
    image: 'https://placehold.it/150x150',
  },{
    id: 6,
    name: 'Dress',
    price: 40,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 7,
    name: 'Shorts',
    price: 25,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 8,
    name: 'Skirt',
    price: 35,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 9,
    name: 'Sweater',
    price: 45,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 10,
    name: 'Jeans',
    price: 50,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 11,
    name: 'T-shirt',
    price: 15,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 12,
    name: 'Sneakers',
    price: 55,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 13,
    name: 'Hoodie',
    price: 40,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 14,
    name: 'Sandals',
    price: 30,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 15,
    name: 'Cap',
    price: 10,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 16,
    name: 'Gloves',
    price: 8,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 17,
    name: 'Blouse',
    price: 30,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 18,
    name: 'Suit',
    price: 100,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 19,
    name: 'Trousers',
    price: 45,
    image: 'https://placehold.it/150x150',
  },
  {
    id: 20,
    name: 'Top',
    price: 25,
    image: 'https://placehold.it/150x150',
  },
]